import "fonts/NotoSansJP-Regular.ttf";
import "fonts/NotoSansJP-Bold.ttf";
import { Theme, AppStates } from "global.slint";
import { DatetimeApp } from "datetime.slint";
import { Home } from "home.slint";
import { Side } from "side.slint";

export component Main inherits Window {
    default-font-family: "Noto Sans JP";
    default-font-size: Theme.font_size;
    default-font-weight: 400;
    width: Theme.display_width;
    height: Theme.display_height;
    background: Theme.active.main_bg;

    HorizontalLayout {
        DatetimeApp { }

        Home { }

        Side { }
    }
}

export { AppStates }