import "./fonts/NotoSansJP-Regular.ttf";
import "./fonts/NotoSansJP-Bold.ttf";
import { StandardButton } from "std-widgets.slint";

enum TileOpenStatus {
    Normal,
    Main,
    Sub,
}

enum Theme {
    Light,
    Dark,
}

enum WifiStatus {
    Add,
    Bad,
    Off,
    Excellent,
    Good,
    Fair,
    Poor
}

export global AppTheme {
    out property <Theme> theme: Theme.Dark;
    out property <int> display_width: 1920;
    out property <int> display_height: 720;
    out property <int> font_size: 24;
    out property <int> grid_spacing: root.font_size * 1.5;
    out property <int> app_size: root.display_height / 2 - root.grid_spacing;
}

export global AppState {
    in-out property <int> name;
    property <TileOpenStatus> open_status: TileOpenStatus.Normal;
}

struct TileData {
    can_use: bool,
    is_open: bool,
}

component Tile inherits Rectangle {
    in property <TileData> current_data: { can_use: false, is_open: false };

    width: AppTheme.app_size * 1phx;
    height: AppTheme.app_size * 1phx;
    background: #0c4a6e;
    border-radius: 1rem;
}

struct WeatherDataUi {
    temp: string,
    humidity: string,
    pressure: string,
}

component RoomTempTile inherits Tile {
    in property <WeatherDataUi> weather_data;

    if !(root.current_data.can-use): Text {
        text: "現在ご利用できません";
        font-size: 1.2rem;
    }

    if (root.current_data.can-use): Text {
        text: "\{root.weather_data.temp}℃";
    }
}

struct DatetimeState {
    Y: string,
    M: string,
    D: string,
    h: string,
    m: string,
    s: string,
}

component DatetimeTile inherits Rectangle {
    in property <TileData> current_data;
    in property <DatetimeState> datetime;

    horizontal-stretch: 1;
    height: 100%;

    Text {
        text: "\{root.datetime.Y}/\{root.datetime.M}/\{root.datetime.D} \{root.datetime.h}:\{root.datetime.m}:\{root.datetime.s}";
        font-size: 2rem;
        font-weight: 700;
    }
}

export component App inherits Window {
    default-font-family: "Noto Sans JP";
    default-font-size: AppTheme.font_size * 1phx;
    width: AppTheme.display_width * 1phx;
    height: AppTheme.display_height * 1phx;

    in property <DatetimeState> datetime;
    in property <bool> can_bme_use;
    in property <WeatherDataUi> bme_result;
    in property <WifiStatus> wifi_status;

    HorizontalLayout {
        DatetimeTile {
            datetime: datetime;
        }

        grid := GridLayout {
            height: 100%;
            width: (AppTheme.app_size * 2 + AppTheme.grid_spacing * 3) * 1phx;
            spacing: AppTheme.grid_spacing * 1phx;
            padding: AppTheme.grid_spacing * 1phx;

            RoomTempTile {
                current_data: { can_use: can_bme_use };
                weather_data: bme_result;
            }

            Tile { }

            Tile { }

            Tile { }
        }

        VerticalLayout {
            alignment: end;
            width: 2rem;
            height: 100%;

            setting := Image {
                source: @image-url("./icons/setting.svg");
            }

            wifi_icon := Image {
                source: @image-url("./icons/wifi-add.svg");
                states [
                    wifi-add when wifi_status == WifiStatus.Add: {
                        source: @image-url("./icons/wifi-add.svg");
                    }
                    wifi-bad when wifi_status == WifiStatus.Bad: {
                        source: @image-url("./icons/wifi-bad.svg");
                    }
                    wifi-off when wifi_status == WifiStatus.Off: {
                        source: @image-url("./icons/wifi-off.svg");
                    }
                    wifi-excellent when wifi_status == WifiStatus.Excellent: {
                        source: @image-url("./icons/wifi-excellent.svg");
                    }
                    wifi-good when wifi_status == WifiStatus.Good: {
                        source: @image-url("./icons/wifi-good.svg");
                    }
                    wifi-fair when wifi_status == WifiStatus.Fair: {
                        source: @image-url("./icons/wifi-fair.svg");
                    }
                    wifi-poor when wifi_status == WifiStatus.Poor: {
                        source: @image-url("./icons/wifi-poor.svg");
                    }
                ]
            }
        }
    }
}
