import "fonts/Inter-Regular.ttf";
import "fonts/Inter-Light.ttf";
import { AppStates, Theme } from "global.slint";
export component DatetimeApp inherits Rectangle {
    horizontal-stretch: 1;
    height: 100%;

    VerticalLayout {
        alignment: center;

        HorizontalLayout {
            property <length> time_font_size: 8rem;
            property <length> sec_font_size: 5rem;

            alignment: center;
            spacing: 1rem;

            Text {
                text: AppStates.datetime.h + ":" + AppStates.datetime.m;
                font-family: "Inter";
                font-weight: 200;
                font-size: time_font_size;
                color: Theme.active.main-txt;
            }

            VerticalLayout {
                width: sec_font_size * 0.7 * 2;
                alignment: end;
                padding-bottom: 0.7rem;
                Text {
                    text: AppStates.datetime.s;
                    font-family: "Inter";
                    font-weight: 400;
                    font-size: sec_font_size;
                    color: Theme.active.main-txt;
                }
            }
        }
    }
}
