enum ClrThemeType {
    Slate,
    Gray, 
    Zinc, 
    Neutral,
    Stone,
    Taupe,
    Mauve,
    Mist,
    Olive
}

struct ClrProps {
    main_bg: color,
    sub_bg: color,
    app_bg: color,
    main_txt: color,
    app_txt: color,
}

export global Theme {
    out property <physical-length> display_width: 1920phx;
    out property <physical-length> display_height: 720phx;
    out property <physical-length> font_size: 24phx;
    out property <physical-length> grid_spacing: font_size * 1.5;
    out property <physical-length> app_size: (display_height - grid_spacing * 3) / 2;
    out property <physical-length> app_size_open: display_height - grid_spacing * 2;
    out property <physical-length> home_width: (Theme.app_size * 2 + Theme.grid_spacing * 3);

    in-out property <bool> is_light: false;
    in-out property <ClrThemeType> clr_theme: ClrThemeType.Taupe;

    pure function get_active_props(t: ClrThemeType) -> ClrProps {
        if (t == ClrThemeType.Slate) {
            return slate;
        }
        if (t == ClrThemeType.Gray) {
            return gray;
        }
        if (t == ClrThemeType.Zinc) {
            return zinc;
        }
        if (t == ClrThemeType.Neutral) {
            return neutral;
        }
        if (t == ClrThemeType.Stone) {
            return stone;
        }
        if (t == ClrThemeType.Taupe) {
            return taupe;
        }
        if (t == ClrThemeType.Mauve) {
            return mauve;
        }
        if (t == ClrThemeType.Mist) {
            return mist;
        }
        return olive;
    }

    out property <ClrProps> active: get_active_props(clr_theme);

    out property <ClrProps> slate: {
        main_bg: is_light ? #cbd5e1 : #1e293b,
        sub_bg: is_light ? #94a3b8 : #334155,
        app_bg: is_light ? #64748b : #475569,
        main_txt: is_light ? #1e293b : #e2e8f0,
        app_txt: is_light ? #e2e8f0 : #cbd5e1,
    };
    out property <ClrProps> gray: {
        main_bg: is_light ? #d1d5db : #1f2937,
        sub_bg: is_light ? #9ca3af : #374151,
        app_bg: is_light ? #6b7280 : #4b5563,
        main_txt: is_light ? #1f2937 : #e5e7eb,
        app_txt: is_light ? #e5e7eb : #d1d5db,
    };
    out property <ClrProps> zinc: {
        main_bg: is_light ? #d4d4d8 : #27272a,
        sub_bg: is_light ? #a1a1aa : #3f3f46,
        app_bg: is_light ? #71717a : #52525b,
        main_txt: is_light ? #374151 : #e4e4e7,
        app_txt: is_light ? #e4e4e7 : #d4d4d8,
    };
    out property <ClrProps> neutral: {
        main_bg: is_light ? #d4d4d4 : #262626,
        sub_bg: is_light ? #a3a3a3 : #404040,
        app_bg: is_light ? #737373 : #525252,
        main_txt: is_light ? #262626 : #e5e5e5,
        app_txt: is_light ? #e5e5e5 : #d4d4d4,
    };
    out property <ClrProps> stone: {
        main_bg: is_light ? #d6d3d1 : #292524,
        sub_bg: is_light ? #a8a29e : #44403c,
        app_bg: is_light ? #78716c : #57534e,
        main_txt: is_light ? #292524 : #e7e5e4,
        app_txt: is_light ? #e7e5e4 : #d6d3d1,
    };
    out property <ClrProps> taupe: {
        main_bg: is_light ? #d8d2d0 : #2b2422,
        sub_bg: is_light ? #aba09c : #473c39,
        app_bg: is_light ? #7c6d67 : #5b4f4b,
        main_txt: is_light ? #2b2422 : #e8e4e3,
        app_txt: is_light ? #e8e4e3 : #d8d2d0,
    };
    out property <ClrProps> mauve: {
        main_bg: is_light ? #d7d0d7 : #2a212c,
        sub_bg: is_light ? #a89ea9 : #463947,
        app_bg: is_light ? #79697b : #594c5b,
        main_txt: is_light ? #2a212c : #e7e4e7,
        app_txt: is_light ? #e7e4e7 : #d7d0d7,
    };
    out property <ClrProps> mist: {
        main_bg: is_light ? #d0d6d8 : #22292b,
        sub_bg: is_light ? #9ca8ab : #394447,
        app_bg: is_light ? #67787c : #4b585b,
        main_txt: is_light ? #22292b : #e3e7e8,
        app_txt: is_light ? #e3e7e8 : #d0d6d8,
    };
    out property <ClrProps> olive: {
        main_bg: is_light ? #d8d8d0 : #2b2b22,
        sub_bg: is_light ? #abab9c : #474739,
        app_bg: is_light ? #7c7c67 : #5b5b4b,
        main_txt: is_light ? #2b2b22 : #e8e8e3,
        app_txt: is_light ? #e8e8e3 : #d8d8d0,
    };
}

export struct DatetimeState {
    h: string,
    m: string,
    s: string,
}


export enum WifiStatus {
    Add,
    Bad,
    Off,
    Excellent,
    Good,
    Fair,
    Poor
}

export enum AppTypes {
    None,
    RoomTemp,
    Other,
}

export struct AppData {
    app_type: AppTypes,
    slot: int,
}

export struct Position {
    x: length,
    y: length,
}

export struct WeatherDataUi {
    temp: string,
    humidity: string,
    pressure: string,
}

export global AppStates {
    in-out property <DatetimeState> datetime;
    in-out property <WifiStatus> wifi_status;
    in-out property <[AppData]> apps: [
        {
            app_type: AppTypes.RoomTemp,
            slot: 3,
        },
        {
            app_type: AppTypes.Other,
            slot: 4,
        },
    ];
    in-out property <int> num_page: 1;
    in-out property <AppTypes> opne_app: AppTypes.None;
    in property <bool> can_bme_use;
    in property <WeatherDataUi> bme_result;
}