import { AppStates, AppTypes, Position, Theme } from "global.slint";

component AppBase inherits Rectangle {
    in property <AppTypes> app_type: AppTypes.Other;
    out property <bool> is_open: AppStates.open_app == root.app_type;
    width: 100%;
    height: 100%;

    callback open_touch();

    TouchArea {
        visible: is_open || AppStates.open_app == AppTypes.None;
        clicked => {
            if is_open {
                open_touch();
            } else {
                AppStates.open_app = app_type;
            }
        }
    }
}

component RoomTempApp inherits AppBase {
    app_type: AppTypes.RoomTemp;

    open_touch => {
        debug("タッチされました");
    }

    if !AppStates.can_bme_use: Text {
        color: Theme.active.app_txt;
        text: "現在ご利用できません";
        font-size: 1.2rem;
    }

    if AppStates.can_bme_use: Text {
        text: "\{AppStates.bme_result.temp}℃";
    }
}

component App inherits Rectangle {
    in property <AppTypes> app_type;
    in property <int> slot;

    property <Position> pos: {
        x: floor(slot / 4) * Theme.home_width + Theme.grid_spacing + mod(slot, 2) * (Theme.app_size + Theme.grid_spacing),
        y: Theme.grid_spacing + floor(mod(slot, 4) / 2) * (Theme.app_size + Theme.grid_spacing),
    };
    property <Position> pos_open: {
        x: floor(slot / 4) * Theme.home_width + Theme.grid_spacing,
        y: Theme.grid_spacing,
    };
    property <duration> toggle_duration: 250ms;
    property <bool> is_open: AppStates.open_app == root.app_type;
    property <string> title: "アプリ";

    states [
        room-temp when app_type == AppTypes.RoomTemp: {
            title: "室温";
        }
    ]

    x: is_open ? pos_open.x : pos.x;
    y: is_open ? pos_open.y : pos.y;
    background: Theme.active.app_bg;
    width: is_open ? Theme.app_size_open : Theme.app_size;
    height: is_open ? Theme.app_size_open : Theme.app_size;
    border-radius: 1.5rem;
    clip: true;

    animate x, y, width, height {
        duration: toggle_duration;
        easing: ease-out-quart;
    }

    main := VerticalLayout {
        padding: is_open ? Theme.grid_spacing : 0;
        spacing: is_open ? 0.5rem : 0;

        animate padding, spacing { duration: toggle_duration / 2; }

        header := Rectangle {
            width: 100%;
            height: is_open ? 2rem : 0;
            opacity: is_open ? 1 : 0;

            animate opacity {
                duration: toggle_duration / 2;
                delay: is_open ? toggle_duration / 2 : 0;
            }

            Image {
                x: 0;
                y: 0;
                width: 2rem;
                height: 2rem;
                source: @image-url("./icons/back.svg");

                TouchArea {
                    clicked => {
                        AppStates.open_app = AppTypes.None;
                    }
                }
            }

            Text {
                x: 0;
                y: 0;
                width: 100%;
                height: 100%;
                text: title;
                font-size: 1.5rem;
                horizontal-alignment: center;
                vertical-alignment: center;
            }
        }

        container := Rectangle {
            vertical-stretch: 1;
            if app_type == AppTypes.RoomTemp: RoomTempApp { }
            if app_type == AppTypes.Other: AppBase { }
        }
    }
}

export component Home inherits Rectangle {
    property <int> current_page: 0;

    clip: true;
    width: Theme.home_width;
    height: 100%;

    sgr := SwipeGestureHandler {
        handle-swipe-right: AppStates.open_app == AppTypes.None;
        handle-swipe-left: AppStates.open_app == AppTypes.None;

        swiped => {
            let delta_x = self.current-position.x - self.pressed-position.x;
            let width = root.width;

            let ratio = -delta_x / width;

            let base_move = floor(Math.abs(ratio)) * (ratio > 0 ? 1 : -1);
            let rem = ratio - base_move;

            let extra = (Math.abs(rem) > 0.25) ? ((rem > 0) ? 1 : -1) : 0;

            let target_page = root.current_page + base_move + extra;

            root.current_page = Math.max(0, Math.min(AppStates.num_page, target_page));
        }

        contant := Rectangle {
            property <length> position: - current-page * root.width;
            animate position {
                duration: 200ms;
                easing: ease-out-circ;
            }
            property <physical-length> max_left_offset: root.current_page * root.width;
            property <physical-length> max_right_offset: (AppStates.num_page - root.current_page) * root.width;
            property <physical-length> limit: root.width / 5;
            property <physical-length> delta_x: sgr.current-position.x - sgr.pressed-position.x;
            property <physical-length> over_delta: (delta_x > max_left_offset) ? (delta_x - max_left_offset) : (delta_x < -max_right_offset) ? (delta_x + max_right_offset) : 0px;
            property <physical-length> elastic_offset: limit * (over_delta / (Math.abs(over_delta) + limit * 2));
            property <physical-length> swipe-offset;

            width: Theme.home_width * (AppStates.num_page + 1);
            height: 100%;
            x: position + swipe-offset;
            states [
                swiping when sgr.swiping: {
                    swipe-offset: (delta_x > max_left_offset) ? (max_left_offset + elastic_offset) : (delta_x < -max_right_offset) ? (-max_right_offset + elastic_offset) : delta_x;
                    out {
                        animate swipe-offset {
                            duration: 200ms;
                            easing: ease-out-circ;
                        }
                    }
                }
            ]

            for app in AppStates.apps: App {
                app_type: app.app_type;
                slot: app.slot;
            }
        }

        HorizontalLayout {
            width: 100%;
            height: Theme.grid_spacing;
            padding: 0.25rem;
            alignment: center;
            y: Theme.display_height - Theme.grid_spacing;

            Rectangle {
                width: layout.preferred-width;
                height: 100%;
                background: Theme.active.sub-bg;
                border-radius: 0.5rem;
                opacity: sgr.swiping ? 1 : 0;

                animate opacity {
                    duration: sgr.swiping ? 30ms : 75ms;
                    delay: sgr.swiping ? 0 : 700ms;
                }

                layout := HorizontalLayout {
                    property <length> space: 0.4rem;
                    alignment: center;
                    spacing: space;
                    padding-left: space;
                    padding-right: space;

                    for i in AppStates.num_page + 1: Rectangle {
                        property <bool> is_active: sgr.swiping ? Math.round(-contant.x / Theme.home_width) == i : i == current_page;
                        property <length> size: 0.3rem;
                        y: (parent.height - size) / 2;
                        width: size;
                        height: size;
                        background: Theme.active.app-txt;
                        opacity: is_active ? 1 : 0.4;
                        border-radius: size;

                        animate opacity { duration: 120ms; }
                    }
                }
            }
        }
    }
}

